version: '3.8'

services:
  allure-service:
    build:
      context: .
    pid: host
    container_name: allure-service
    image: allure-service:latest
    pull_policy: always
    restart: always
    ports:
      - "5050:5050"
    volumes:
      - ./.AppData/projects:/app/AppData/projects
      - ./allure-service/reports/csv:/app/AppData/reports/csv
      - ./allure-service/:/app/BackupData
      # - ./allure/config/allure.yml:/allure/config/allure.yml # optional custom allure config to activate custom-logo-plugin
      # - ./allure/plugins/custom-logo-plugin:/allure/plugins/custom-logo-plugin # put your custom-logo-plugin here
    environment:
      APP_MODE: release
      KEEP_RESULTS_HISTORY: true
      KEEP_HISTORY_LATEST: 3
