version: '3.8'

services:
  allure-service-go:
    pid: host
    container_name: allure-service-go
    image: ${IMAGE_NAME}
    pull_policy: always
    restart: always
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/.AppData/projects:/app/AppData/projects
      - /Storage/allure-service-go/reports/csv:/app/AppData/reports/csv
      - /Storage/allure-service-go/:/app/BackupData
      - ${PWD}/allure/config/allure.yml:/allure/config/allure.yml
      - ${PWD}/allure/plugins/custom-logo-plugin:/allure/plugins/custom-logo-plugin
    environment:
      APP_MODE: release
      KEEP_RESULTS_HISTORY: true
      KEEP_HISTORY_LATEST: 3
