version: '3.8'

services:
  allure-service-go:
    container_name: allure-service-go
    image: registry-intl.ap-southeast-5.aliyuncs.com/dana/allure-service-go:latest
    #pull_policy: always
    restart: always
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/.AppData/projects:/allure/AppData/projects
    env_file:
      - .env
