version: '3.8'

services:
  allure-service-go:
    build:
      context: .
    pid: host
    container_name: allure-service-go
    image: allure-service-go:latest
    pull_policy: always
    restart: always
    ports:
      - "5050:5050"
    volumes:
      - ./.AppData/projects:/app/AppData/projects
      - ./allure-service-go/reports/csv:/app/AppData/reports/csv
      - ./allure-service-go/:/app/BackupData
      # - ./allure/config/allure.yml:/allure/config/allure.yml
      # - ./allure/plugins/custom-logo-plugin:/allure/plugins/custom-logo-plugin
    environment:
      APP_MODE: release
      KEEP_RESULTS_HISTORY: true
      KEEP_HISTORY_LATEST: 3
