info:
  contact: {}
paths:
  /config:
    get:
      consumes:
      - '*/*'
      description: Get app config
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get App Config
      tags:
      - General
  /generate-report:
    get:
      parameters:
      - description: projectId
        in: query
        name: project_id
        required: true
        type: string
      - description: executionName
        in: query
        name: execution_name
        type: string
      - description: executionName
        in: query
        name: execution_from
        type: string
      - description: executionName
        in: query
        name: execution_type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Generate report from sent results
      tags:
      - Reports
  /projects:
    get:
      consumes:
      - '*/*'
      description: Get All projects
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get All projects
      tags:
      - Projects
  /projects/{project_id}:
    delete:
      consumes:
      - '*/*'
      description: Delete Project
      parameters:
      - default: default
        description: default
        in: path
        name: project_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete Project
      tags:
      - Projects
    get:
      consumes:
      - '*/*'
      description: Get Project By ID
      parameters:
      - default: default
        description: default
        in: path
        name: project_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get Project By ID
      tags:
      - Projects
    post:
      consumes:
      - '*/*'
      description: Create Project
      parameters:
      - default: default
        description: default
        in: path
        name: project_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create Project
      tags:
      - Projects
  /projects/{project_id}/reports/{path}:
    get:
      consumes:
      - '*/*'
      description: Get Path in a project directory
      parameters:
      - default: default
        description: default
        in: path
        name: project_id
        required: true
        type: string
      - default: latest/widgets/summary.json
        description: default
        in: path
        name: path
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Get Path in a project directory
      tags:
      - Projects
  /send-results:
    post:
      consumes:
      - multipart/form-data
      description: Send allure result files to server
      parameters:
      - description: projectId
        in: query
        name: project_id
        required: true
        type: string
      - description: create project if not exists
        in: query
        name: force_project_creation
        type: boolean
      - collectionFormat: csv
        description: result files
        in: formData
        items:
          type: file
        name: files
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Send results
      tags:
      - Reports
swagger: "2.0"
